version: '3'
services:
  orderservice:
    build:
      context: .
      dockerfile: orderservice/Dockerfile
    ports:
      - "8081:8081"
  userservice:
    build:
      context: .
      dockerfile: userservice/Dockerfile
    ports:
      - "8082:8082"
